  name: Ejecutar acciones controladas en AWS desde Github Actions
  on:
    push:
      branches:
        - main

  env:
    AWS_ROLE: arn:aws:iam::755990962817:role/github-actions-oidc-democicd-role

  jobs:
    demo-cicd-job:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.MY_GITHUB_TOKEN }}
            
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
  
        - name: Install dependencies
          run: npm ci
  
        - name: Build project
          run: npm run build 
        
