  name: Ejecutar acciones controladas en AWS desde Github Actions
  on:
    push:
      branches:
        - main

  env:
    AWS_ROLE: arn:aws:iam::755990962817:role/github-actions-oidc-democicd-role

  jobs:
    demo-cicd-job:
      runs-on: ubuntu-latest
      permissions:
        id-token: write
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.MY_GITHUB_TOKEN }}
            
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
  
        - name: Install dependencies
          run: npm ci
  
        - name: Build project
          run: npm run build 
          
        - name: Configure AWS credentials from OIDC
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ env.AWS_ROLE }}
            aws-region: us-east-2

        - name: Determine S3 Bucket
          id: bucket
          run: |
            if [ "${{ github.ref }}" == "refs/heads/main" ]; then
              echo "bucket_name=${{ secrets.S3_BUCKET_PROD }}" >> $GITHUB_OUTPUT
            elif [ "${{ github.ref }}" == "refs/heads/develop" ]; then
              echo "bucket_name=${{ secrets.S3_BUCKET_DEV }}" >> $GITHUB_OUTPUT
            fi

        - name: Deploy to S3
          run: |
            aws s3 sync ./.next/ s3://${{ steps.bucket.outputs.bucket_name }} --delete
